name: Auto Tag on Commit

on:
  pull_request:
    types: [closed]
    branches:
      - SB
  

jobs:
  build_SB_PULL_REQUEST:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ secrets.BOT_TOKEN2 }}

      - name: Generate Git Tag
        id: generate_tag
        run: |
        
         HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
         echo "Head ref: $HEAD_BRANCH"

          # Find the latest tag if available,
          
            if [ "$HEAD_BRANCH" == "QA" ]; then
               LATEST_TAG=$(git describe --tags --abbrev=0 "origin/QA" || echo "")
               echo "Latest tag: $LATEST_TAG"

          else
             LATEST_TAG=$(git describe --tags --abbrev=0 "origin/SB" || echo "")
             echo "Latest tag: $LATEST_TAG"

          fi
            Branch_name="sb"

          # If no tag found in branch SB,
          if [ -z "$LATEST_TAG" ]; then
            
                NEW_VERSION="1.0.0.p1"
      
          else
            # Extract the version number and branch name from the latest tag
            VERSION_BRANCH=$(echo "$LATEST_TAG" | cut -d'_' -f1)
            VERSION=$(echo "$VERSION_BRANCH" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
            BRANCH_NAME=$(echo "$LATEST_TAG" | cut -d'_' -f2)

            NEW_VERSION=$(echo "$VERSION" | awk -F'.' '{print $1 "." $2 "." $3}')

            # Construct the new tag

              if [ "$HEAD_BRANCH" == "QA" ]; then  
                NEW_TAG="v${NEW_VERSION}_$Branch_name"   
              else
                # NEW_VERSION=$(echo "$VERSION" | awk -F'.' '{print $1 "." $2 "." $3 +1 }')
                NEW_TAG="v${NEW_VERSION}.p1_$Branch_name" 
              fi
          fi

          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Push Git Tag
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN2 }}
        run: |
          git config user.name "Abisheck2002"
          git config user.email "abisheck.g@netxd.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG
